packages:
  - 'backend'
  - 'frontend'
  - 'share-lib'
allowBuilds:
  bcrypt: true
  esbuild: true
  unrs-resolver: true
onlyBuiltDependencies:
  - bcrypt
  - unrs-resolver
  - esbuild
  - '@nestjs/core'
